name: Deployment-of-python-app
on:
  pull_request:
    paths:
      - '**.py'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This has been triggered ${{ github.event_name }} event"
      - run: echo "This job is running on ${{ runner.os }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Lint with pylint
        run: |
          python lint_test.py
      - name: Build container
        run: |
          echo "Building..."
          sleep 10
      - run: echo "Done!"
  hello-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: ./hello-actions@v1
